### ISSUE TITLE
Usage of the IdGenerator should never be exclusively compiletime or non compiletime

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstStdlib2#12]
Right now, stdlib has at least one instance where .next() is called on an IdGenerator object exclusively in compiletime (I noticed it in OnUnitEnterLeave), and there could be more, I think this should be sanitized and I was thinking about tackling this problem but I decided to first discuss this with everyone.

IdGenerator (especially when using the instances we're supposed to use, like ABIL_ID_GEN) can be used both in compiletime and out of it, but when it is used solely in one mode but not in the other one, it creates Id bugs in code. Everything shifts by the number of times that the id wasn't incremented in both compiletime and out of it, which is why I think we should sanitize this issue in the stdlib at least.

**Comment by Frotty** [comment]
The only "unsafe" .next() call in the stdlib is inside the HeroPreset package which can be removed.
Other than that there is no easy way to "sanitize" this. Using id-generators inside the compiletime expressions is the way to go.
