### ISSUE TITLE
I figured out a bizarre solution for OnUnitEnterLeave that made it work for me

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstStdlib2#13]
Apparently, moving the constant to ABOVE the init block solved the issue. The original issue I have had is, that the ABIL_ID constant got initialized too late, so everything that followed off from it (that required this to be initialized) just used the value of zero.

Before:
```
init
   ...do things...

constant ABILITY_ID = compiletime(ABIL_ID_GEN.next())
```

After
```
constant ABILITY_ID = compiletime(ABIL_ID_GEN.next())

init
    ...do things...
```

I think this is a flaw in how the compiler looks at the code, even if the constant is bellow the init block, it should be dealt with first.

I did a clean install of everything, and the bug where I create a new project and a green "Defend" icon shows up in bottom left of every unit's interface still persists. This is an actual issue, it happens in my project, and it happens in a newly generated project. I hope someone else can also test this directly to see how it works for them in the latest version of the compiler/stdlib.

Also:

```
GroupEnumUnitsInRect(ENUM_GROUP, boundRect, null)
nullTimer(() -> begin
	for u from ENUM_GROUP
		if u == null
			break
		u..addAbility(ABILITY_ID)..makeAbilityPermanent(ABILITY_ID, true)
		eventTrigger.evaluate()
```

Why does this even use the null timer? If I understand, the idea is that you can create the unit in the map init block, and then this "catch all units on the map" will catch it, but under the circumstances that UnitIndexer is initialized AFTER the code in question, it will miss out some units, and this can randomly happen from my experience (some packages will create units that are caught by this and indexed properly, some will leave unindexed units).

This version works for me:

```
GroupEnumUnitsInRect(ENUM_GROUP, boundRect, null)
for u from ENUM_GROUP
	if u == null
		break
	u..addAbility(ABILITY_ID)..makeAbilityPermanent(ABILITY_ID, true)
	eventTrigger.evaluate()`
```
So I have the following questions:

1) Would it actually be okay to just remove the timer closure here completely since it can produce bugs, while it probably exists just to make catching units created in map initialization faster? I removed the closure in my project, put the constant above the init block, and suddenly everything works. Would this be problematic if I had more units on the map or created more units in the init blocks of various packages I have?

2) Is there any particular reason why the constant was bellow the init block, and even beside that, are constants bellow the init block supposed to be initialized AFTER the init block? If this happens for me but not for others, what the hell is wrong with me, my installation or anything? It just sounds so bizarre, so please, can anyone test this out on their part? See if the constant ABIL_ID is actually initialized at the point that the init block is run (why would it even need to be initialized, isn't it a constant in implementation too? shouldn't preprocessor just replace everything?)

**Comment by Cokemonkey11** [comment]
@Frotty this issue has no context and HT says you know what he's talking about. Can you take a look?

**Comment by Cokemonkey11** [comment]
Okay, I got some more info. Two things:

* compiler bug that init block can get confused only sometimes if `constant` value is before/after init block. I think @Frotty should confirm and possible fix or defer to peq

* This line is also incorrect - https://github.com/wurstscript/WurstStdlib2/blob/master/wurst/event/OnUnitEnterLeave.wurst#L55

It depends that no unit is created during initialisation after this init function, which is not something you can rely on.

HT already has a fix for that. So, @IgorSamurovic I suggest you make a pull request and then I can review.

**Comment by Frotty** [comment]
The PR is merged.
