### ISSUE TITLE
player.is_human

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#139]
Seems useful, I find myself writing it pretty often:

```
function player.is_human() returns bool
	return this.getSlotState() == PLAYER_SLOT_STATE_PLAYING and
		   this.getController() == MAP_CONTROL_USER
```

**Comment by Frotty** [comment]
https://github.com/wurstscript/WurstStdlib2/blob/8647a6e70e7ee43e29e669d386c7eb06f47adc5f/wurst/_handles/Player.wurst#L120

**Comment by Cokemonkey11** [comment]
Thanks!
