### ISSUE TITLE
vec2.grow_to_rect

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#140]
Basically a better version of `RectFromCenterSizeBJ`

```
function vec2.grow_to_rect(real nominal_radius) returns rect
	return Rect(this.x - nominal_radius, this.y - nominal_radius, this.x + nominal_radius, this.y + nominal_radius)
```

**Comment by Frotty** [comment]
You could make a PR if you already provide the function ;)
I don't think the name is ideal, but otherwise useful. We use this in the stdlib already in ClosureForGroups.

**Comment by Cokemonkey11** [comment]
> You could make a PR if you already provide the function

If you are approving it as useful then sure

> I don't think the name is ideal, but otherwise useful.

How do you feel about `vec2.withRadiusRect(real nominalRadius)`?

> We use this in the stdlib already in ClosureForGroups.

I guess you mean it would be useful here? https://github.com/wurstscript/WurstStdlib2/blob/master/wurst/closures/ClosureForGroups.wurst#L157

**Comment by Frotty** [comment]
> How do you feel about vec2.withRadiusRect(real nominalRadius)?

Yea, sounds about right. maybe `vec2.toRectWithRadius(real rad)`. feel free to make a pr.
