### ISSUE TITLE
vec2.is_shallow_water

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#141]
this and many other similar methods seem valuable

```
function vec2.is_shallow_water() returns bool
	return (
		not IsTerrainPathable(this.x, this.y, PATHING_TYPE_FLOATABILITY) and
		not IsTerrainPathable(this.x, this.y, PATHING_TYPE_WALKABILITY)
	)
```

**Comment by Frotty** [comment]
https://github.com/wurstscript/WurstStdlib2/blob/8647a6e70e7ee43e29e669d386c7eb06f47adc5f/wurst/util/TerrainUtils.wurst#L46

**Comment by Cokemonkey11** [comment]
@Frotty why is there a check here for buildability?
