### ISSUE TITLE
HashList.has(int index)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#142]
I took a look but I don't see an obvious way to implement it, but it would be nice to have.

On the same topic, `HashList::get_or(int index, T default)`, `HashList::get_or(T elem, T default)`, and `HashList::has(int index)` are all missing and would be useful.

https://github.com/peq/wurstStdlib/blob/master/wurst/data%20structures/LinkedHashMap.wurst

LinkedHashMap might be more appropriate for some of my requirements

**Comment by Frotty** [comment]
I think the naming should be different and not overloaded, but sure, those can be useful sometimes.

> I don't see an obvious way to implement it

Why? As far as I see it `has(int index)` is just `ht.hasInt(this castTo int, index)`. The other functions should be easy then.

**Comment by Cokemonkey11** [comment]
> I think the naming should be different and not overloaded, but sure, those can be useful sometimes.

So, at present there's `get(int)` and `has(T)`. I'm happy to avoid overloading, but this probably is already an API hazard?

Maybe:

- Deprecate `has(T)`
- Add `HashList::hasMember(T)`
- Add `HashList::hasIndex(int)`
- Deprecate `get(int)`
- Add `HashList::getMember(T)`
- Add `HashList::getIndex(int)`

And then my convenience methods:

- Add `HashList::getMemberOr(T, T)` (Is this actually useful?)
- Add `HashList::getIndexOr(int, T)`

**Comment by Frotty** [comment]
What is the point of `HashList::getMember(T)` ..? If you already have the value, why get it? I think what you want is `remove(T t)` which already exists.

Regarding `hasIndex(int)`, I added `hasAt(int)` to conform with the other index functions.

**Comment by Cokemonkey11** [comment]
> What is the point of HashList::getMember(T)

I think no point, /shrug

> I added hasAt(int) 

Cool 8-)

In hindsight, why is LinkedHashMap not in stdlib2? It's pretty useful imo

**Comment by Frotty** [comment]
> In hindsight, why is LinkedHashMap not in stdlib2? It's pretty useful imo

What's the difference to IterableMap

**Comment by Cokemonkey11** [comment]
idk, here you go though https://github.com/peq/wurstStdlib/blob/master/wurst/data%20structures/LinkedHashMap.wurst
