### ISSUE TITLE
player.getNameColored

### ISSUE THREAD

**Issue by netVoix** [wurstscript/WurstStdlib2#145]
When i try to use player.getNameColored() my map just not start load and warcraft send me to main menu

http://prntscr.com/liv4sp this works, but this http://prntscr.com/liv518 doesnt

**Comment by netVoix** [comment]
Yep. I just created new project and write instead print("Hello world!") print(Player(0).getNameColored()) and map doesnt run, send me to wc3 main menu. Version of wc is 1.26.

**Comment by Frotty** [comment]
1.26 version is the problem

**Comment by flameleo11** [comment]
ah, which version works with not this problem ？

**Comment by Frotty** [comment]
I guess 1.26 doesn't work because of missing natives / no 24 player support or so.
You could try the pre 1.29 branch https://github.com/wurstscript/WurstStdlib2/tree/pre1.29 and see if that works. You will have to manually check that out.

**Comment by Frotty** [comment]
Any updates on this? Did you get it to work? Anything we can do?

**Comment by Frotty** [comment]
@netVoix @flameleo11

**Comment by netVoix** [comment]
atm I just use my own helper functions for colors.
