### ISSUE TITLE
the hashSet error?

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstStdlib2#147]
it cant pass the unit test
```
class B
    int b
    construct(int b)
        this.b = b
public class AA
    HashSet<B> a = new HashSet<B>()

@Test function aaa()
    let _1 = new B(1)
    let _2 = new B(2)
    let _3 = new B(3)
    let aa = new AA()
    aa.a..add(_1,_2,_3)..remove(_2)
    for i in aa.a
        print(i.b) // print 1 2. it should be 1 3
```

for the `hashSetTests.wurst`
change the last `set.remove(3)` the `3` to `5` and print the set
you can find something
```
	// Test remove
	set.get(0).assertEquals(5)
	set.remove(5)
	set.size().assertEquals(2)

	for i in set
		print(i) // print 5 , 6 now
```

**Comment by PhoenixZeng** [comment]
i try to fix it
by
change the add function and remove function but failed.

**Comment by PhoenixZeng** [comment]
i believe the ele`s pos is in confusion

**Comment by Frotty** [comment]
good catch. The saved positions had an offset of one because size was used after adding element. Pushed a fix and test.

**Comment by PhoenixZeng** [comment]
i think it has more problem because i switched the `super.add...` and `let pos = `  .and then in my case is good . but  the `hashSetTests.wurst` seem to error already

**Comment by Frotty** [comment]
All tests including the one you posted above [succeed](https://travis-ci.org/wurstscript/WurstStdlib2/builds/460141955#L2558).
If you have another test that fails, make a new ticket.
