### ISSUE TITLE
Extension function wrappers for 1.30.2 natives

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstStdlib2#151]
For the additions see: https://github.com/wurstscript/WurstScript/commit/986b70f5b7fbdd1e8138c9f34a3916a03f4a669f

@GetLocalPlayer 😺 ?

**Comment by GetLocalPlayer** [comment]
What?

**Comment by Frotty** [comment]
Patch 1.30.2 is live and changed a few things. Some natives got removed, others added. Stdlib requires some updates and I thought maybe you would be willing to help out 👍

**Comment by GetLocalPlayer** [comment]
Ah, sure.

**Comment by Frotty** [comment]
Thanks @anufis and @GetLocalPlayer ❤️
