### ISSUE TITLE
make destroyDestructableSpeedThreshold in Knockback3 @configurable

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#163]
https://github.com/wurstscript/WurstStdlib2/blob/1449f0b549ba6c6aa74203fb04229368c8a2ade1/wurst/util/Knockback3.wurst#L72

**Comment by Krypt0n** [comment]
![unbenannt](https://user-images.githubusercontent.com/640169/50176661-4ab88200-0300-11e9-89ed-2b56d09953ff.PNG)

ok it works in function calls only ofc, my bad

**Comment by Frotty** [comment]
np, btw are you still working on java casc lib?
