### ISSUE TITLE
in here. Is the ForGroupCallback not be destoried?

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstStdlib2#165]
in `ClosureForGroups`
```
/** Executes the given closure for every unit in this group,
	removing the units from the group as processed */
public function group.forEachFrom(ForGroupCallback cb)
	for u from this
		cb.callback(u)

/** Executes the given closure for every unit in this group,
	keeping all units in the group */
public function group.forEachIn(ForGroupCallback cb)
	for u in this
		cb.callback(u)
```

**Comment by PhoenixZeng** [comment]
2:
`group.iterator()` return a new group.
so that is the different with `forEachFrom` and `forEachIn`

**Comment by PhoenixZeng** [comment]
use this maybe is good
```
public function group.forEachIn(ForGroupCallback cb)
	pushCallback(cb)
	ForGroup(this) ->
		currentCallback().callback(GetEnumUnit())
	popCallback()
```

**Comment by PhoenixZeng** [comment]
@Frotty

**Comment by Frotty** [comment]
yea it's not destroyed. Your fix could probably produce the desired effect.

**Comment by PhoenixZeng** [comment]
i think this not be destroyed  is a bug

**Comment by Frotty** [comment]
not necessarily. The functions differ from the other ones by not using DUMMY_GROUP and instead the one the user provides. They are more general in the sense that you could statically define a closure and pass it as argument to multiple calls.
But yes, in the end it is probably the expected behavior. My only concern is the breaking change I think.

**Comment by PhoenixZeng** [comment]
yes. statically define a closure is good. but more rare (maybe)
the reason of why I should  ask this is this function is lose efficacy when the game time over 30min.(i use it in the damagehandler for chance dual a range damage .)

**Comment by Frotty** [comment]
> yes. statically define a closure is good. but more rare (maybe)

Yes, probably.

> the reason of why I should ask this is this function is lose efficacy when the game time over 30min

Is this related to destroying the closure? You could just destroy it yourself?

**Comment by PhoenixZeng** [comment]
```
Is this related to destroying the closure? You could just destroy it yourself?
```
in this case I use the std-lib `group.forEachIn(ForGroupCallback cb)` .i used not destroy it.
i change it to my impl. and now is good.

if you think destroy it is not necessarily. and then this issue can be end

**Comment by Frotty** [comment]
Why you always closing issues?
I think the change makes sense.

**Comment by PhoenixZeng** [comment]
`Why you always closing issues?`
sorry for that
In my company` project I ask a issue
If the leader agree with it so solve it.
If the leader disagree, so close it. 
I'm used to it.
