### ISSUE TITLE
string.replace results to endless loop if param oldSubstring is empty

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#166]
https://github.com/wurstscript/WurstStdlib2/blob/14e883bac53ba1d29b8a625f63a9ada538251938/wurst/_handles/primitives/String.wurst#L188

If try to replace an empty string you get and nice endless loop :)
Maybe raise an error, or just return the string if oldSubstring  is empty.

![1 2](https://user-images.githubusercontent.com/640169/50466343-41cd4d80-099d-11e9-9edb-8e9f71da3411.PNG)

Btw could you make the timeout of 20s configurable via build settings or something like that?

**Comment by Frotty** [comment]
Nice catch 👍 

> Maybe raise an error, or just return the string if oldSubstring is empty.

Sounds good. PR? 😸 

> Btw could you make the timeout of 20s configurable via build settings or something like that?

In theory yes. Should make another ticket in main repo for that.
