### ISSUE TITLE
forUnitsInRangeCounted does not stop after x counts

### ISSUE THREAD

**Issue by StN-NL** [wurstscript/WurstStdlib2#167]
It appears that forUnitsInRangeCounted does not stop after x counts, it does the same thing as forUnitsInRange.

Example: here it iterates through 5 instead of 3 units:
Code snippet: https://bin.wurstlang.org/wayatoviho.wurst
Picture: https://pasteboard.co/HV2CIIj.png

**Comment by Frotty** [comment]
->stdlib issue. 
The "count" functions use the "count" natrives, it's not the same code.
But @WaterKnight informed me that they are apparently broken.
Will update with a custom implementation.

**Comment by StN-NL** [comment]
Cool!

**Comment by Frotty** [comment]
not done yet <,p
