### ISSUE TITLE
Lastorder causes lag

### ISSUE THREAD

**Issue by Marsunpaisti** [wurstscript/WurstStdlib2#170]
Just adding a package with "import LastOrder" and nothing else causes my map to lag so heavily its totally unplayable right at the start.

**Comment by Frotty** [comment]
hm yeah, looks like order recycling is broken. I will push a fix.
Thanks for report 👍

**Comment by Frotty** [comment]
Okay, was a small bug. Update via setup and it should no longer lagg.
