### ISSUE TITLE
OnUnitEnterLeave

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstStdlib2#172]
https://github.com/wurstscript/WurstStdlib2/blob/7887a5a1e3ecadd703761a7fa00fd716a921508f/wurst/event/OnUnitEnterLeave.wurst#L61

Should be: 
`CreateTrigger()..registerEnterRegion(boundRegion, null)..addCondition(Condition(() -> prepareUnit(GetTriggerUnit())))`

Filtering units aren't considered entered yet, meaning any move applied to a unit during the filtering (using SetUnitX/Y or SetUnitPosition) will re-trigger the enter event for it.

Here is a small script to test the issue (on enter will fire twice for both units).
```
package demo2

import ClosureTimers
import UnitIndexer
import OnUnitEnterLeave

init
    doAfter(1.) -> 
        CreateUnit(players[0],'hpea',0,0,270)
        CreateUnit(players[0],'hhou',0,0,270)

    onEnter() -> 
        print("on enter = "+getEnterLeaveUnit().getName())

    onUnitIndex() -> 
        let u = getIndexedUnit()
        print("on index = "+u.getName())
        u.setPos(u.getPos())
```

**Comment by WareditorGit** [comment]
However, I noticed that this change adds some delay to the event. Meaning a unit will fire the event a bit after its creation and not directly after it. So it might be better to keep it the way it is now and just make sure to not move units during an onEnter or onIndex response.

**Comment by Frotty** [comment]
Thanks for the report 👍 

> However, I noticed that this change adds some delay to the event

What kind of delay are we talking about here? Just different execution order or noticable ingame.

> So it might be better to keep it the way it is now and just make sure to not move units during an onEnter or onIndex response.

Maybe. Why not use index/deindex events? Those should only fire once or?

**Comment by WareditorGit** [comment]
With how it is currently you can do 
```
let u = createUnit(...)
//some things
```
knowing that //some things will be executed after all the onIndex events.
However if we change that like I suggested, it will not be the case. I think it's a 0s delay type of thing.

Yes, the index event will only fire once but if you move the unit in it, it will still fire a second onEnter() event.
Basically, don't move units in those events and everything should be fine :+1:

**Comment by Frotty** [comment]
So what is the conclusion?
Add a hint about it and keep as is?

**Comment by WareditorGit** [comment]
Yeah I think just have a "Keep in mind" comment would be enough. William told me they aren't going to change that behavior because some maps might rely on it (though I doubt it since it's pretty obscure).

**Comment by Frotty** [comment]
>  William told me they aren't going to change that behavior because some maps might rely on it

big words after breaking half the game and still not having fixed it, lol.
But ok then, will do.
