### ISSUE TITLE
primites string charset to int enhance charset

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#179]
https://github.com/wurstscript/WurstStdlib2/blob/aec0c1ab6103bbfa60a5e77f71b450b65df2ba37/wurst/_handles/primitives/String.wurst#L5

maybe make the charset configurable or enhance it by all allowed chars known for wc3?

**Comment by Frotty** [comment]
Isn't that this https://github.com/wurstscript/WurstStdlib2/blob/be3aa21ffe963757e924232c0382e7adbb03f4e9/wurst/util/StringUtils.wurst#L45

**Comment by Krypt0n** [comment]
basically yes

**Comment by Frotty** [comment]
yea I'm not sure why we have both tbh

**Comment by Krypt0n** [comment]
move it on hold to "refactoring", and close its ok
