### ISSUE TITLE
Assets library should have pathing maps (the building footprints)

### ISSUE THREAD

**Issue by Poruft** [wurstscript/WurstStdlib2#180]
Would be nice to be able to access building pathing maps via the Assets library. Not sure if it makes more sense to have:

`PathingMaps.guardtower` (for every building in the game)

or

`PathingMaps.twoByTwo` (for all the rectangular pathing maps)

The building-based option makes it easy for people who know which building they want to mimic, but it isn't as straightforward for people who just want a rectangle. Perhaps both would be neat.

**Comment by Frotty** [comment]
@Poruft 🚁
