### ISSUE TITLE
IterableMap keys is protected

### ISSUE THREAD

**Issue by AndreasVolkmann** [wurstscript/WurstStdlib2#182]
Hi there, thanks for the great tools. 

I was wondering why `IterableMap`'s `keys` is `protected`?
I would like to access my map's keys elsewhere.

**Comment by Frotty** [comment]
You shouldn't ever need to modify the key list per principle, as any outside modification can cause issues. Immutable access is provided via `.iterator()` (for in loop) and `.contains .size` If you want to change the behavior, extend IterableMap in proper OOP fashion. 
If you still think you need it, please state an actual use case example.

**Comment by AndreasVolkmann** [comment]
My use case is that I want to call `copy` and `shuffle` on the keys. 
I don't want to modify the original list. Imo it should be immutable.  

If I am not mistaken, you also know Kotlin. 
The Map interface in the kotlin stdlib provides a read-only set of its keys:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/keys.html#kotlin.collections.Map%24keys

This is what I was looking for.

**Comment by Frotty** [comment]
Yea seems legitimate. You can already do it of course, just build a new list via the iterator and then shuffle it.
I suppose we could add a function that returns a copy of the keys.

**Comment by AndreasVolkmann** [comment]
Ok, I will start by more functions that I am missing and once I hit a certain size we can compare and see if any of these should be included in the stdlib or kept separate.

**Comment by Frotty** [comment]
> Ok, I will start by gathering more functions that I am missing and once I hit a certain size we can compare and see if any of these should be included in the stdlib or kept separate.

Sounds great :) But really the smaller the PR, the better. Easier & faster review results in a faster merge.
Feel free to make a PR even for single functions, as long as they make sense and have proper hotdoc.

Cheers 👍
