### ISSUE TITLE
allow non standard paths for icon of dummy buffs

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#187]
https://github.com/wurstscript/WurstStdlib2/blob/679af4db1001b1d6f7f4fd30731c96977581c354/wurst/objediting/BuffObjEditing.wurst#L30

right now if you want to use that function the path icon path must start with
"ReplaceableTextures" and well at least for me I don't  want to use that folder for everything

**Comment by Frotty** [comment]
Then you want green icons? 🤔

**Comment by Krypt0n** [comment]
well tbh that's a bit shitty then you have 
ReplaceableTextures\\CommandButtonsDisabled
for those
but having all icon for a project in 2 folders is a bit messy
a bit sad that only ReplaceableTextures\\CommandButtons can be subfoldered

**Comment by Frotty** [comment]
Iirc you have to use those folders to avoid green icons, or did that change? 
I suppose it shouldn't be mandatory, what is your suggestion to avoid a breaking change?

**Comment by Krypt0n** [comment]
well you only need that folder for the DIS, cause wc3 will just get all disable buttons (top avoid green icon thus) from "ReplaceableTextures\CommandButtonsDisabled\"
Not sure if it makes sense to have subfolder structure for "normal" icons but not for the "disabled" icons

I can ask some dev to change that in the future, so DIS- button cann go in any folder ...

**Comment by Frotty** [comment]
Ah okay, so you could have an `imports/customfolder/BTNicon.blp` icon and wc3 will try to resolve the disabled variant from `imports/ReplaceableTextures/CommandButtonsDisabled/DISBTNicon.blp` ?
But for disabled only the root `CommandButtonsDisabled` is checked?

**Comment by Krypt0n** [comment]
Yeah correctly

**Comment by Frotty** [comment]
Okay so the only elegant non breaking way I can think about is prefixing your paths with some char like `@` which the preset function will detect and not add the `ReplaceableTextures` prefix, just remove the `@`.
Do you have another idea?
