### ISSUE TITLE
PreloadIO.wurst max packet lengths is wrong

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#188]
https://github.com/wurstscript/WurstStdlib2/blob/0aa2173acff1ba53fa56d70821c9e86fdcfb0548/wurst/file/PreloadIO.wurst#L21

the max packet length should be set to 222 if there are more then 9 players slots, cause then it needs 1 character more in preload

**Comment by Frotty** [comment]
@SamuelMoriarty ?

**Comment by SamuelMoriarty** [comment]
Sounds reasonable to me.

**Comment by Frotty** [comment]
Thanks 👍
