### ISSUE TITLE
TimedLoop: Stop on destroy

### ISSUE THREAD

**Issue by maltebp** [wurstscript/WurstStdlib2#197]
So I was suggesting using the TimedLoop module in TimerUtils for a class which keeps updating, and it seems quite cool.

However, the module doesn't allow that the TimerLoop is stopped at destroying the instance of the implementing class. And this seems rather inconvenient. I want to suggest implementing this "feature" (I will come up with a solution myself) - but is it even needed? Is it _meant_ not to allow this feature because of some other factors?

**Comment by Frotty** [comment]
The timed loop module adds functions to your class that you have to call instead of destroy.
See `stopTimedLoop` and `stopTimedLoopAndDestroy`.

**Comment by maltebp** [comment]
So I'm never meant to use the 'destroy' call within the instance of the implementing class?

**Comment by maltebp** [comment]
So I just tested that, and it seems to be the case. Fair enough, if that's the design of it, it just doesn't seem very intuitive. is there a design reason for doing it this way rather than just stopping loop when destroying the instance?

**Comment by Frotty** [comment]
Btw what do you mean by "not allow" ?
All I see in the code is a warning `Log.warn("Destroyed Instance using TimedLoop before stopping the Loop")` that should tell you to stop the loop before destroying.
Is that what you mean?
Guess it could be removed.

**Comment by maltebp** [comment]
Not quite what I meant. I got an trying to destroy an object twice. But I must have made a mistake in my code which I fixed, because it shows no more, and I can't replicate the error. 😮 

This just leaves the "problem" to the warning, which I suppose I can just ignore and disable through start run arguments? If that's the case, then this issue can be closed

**Comment by maltebp** [comment]
Alright I think I have found the bug that have caused me trouble. The problem occurs when you destroy the object implementation.

This is the onDestroy in the TimedLoop:

'ondestroy
		if mode != Mode.PAUSED
			stopTimedLoop()
			Log.warn("Destroyed Instance using TimedLoop before stopping the Loop")'

It only tells that it shouldn't be stopped. It not actually stopping it. And the update function runs the specific loop instance's 'onTimedLoop()' function _before_ it checks if that particular instance should be stopped:

'private static function onExpire() returns boolean
		int i = instanceCount - 1
		while i >= 0
			thistype t = instances[i]

			t.onTimedLoop()
			if t.mode != Mode.RUNNING
				instanceCount--
				instances[i] = instances[instanceCount]
				if t.mode == Mode.STOPPED_FOR_GOOD
					t.mode = Mode.PAUSED
					destroy t
				else
					t.mode = Mode.PAUSED
...'

This ultimately leads to the TimedLoop update function to call onTimedLoop() on an object which doesn't exist, and throws this error:
![image](https://user-images.githubusercontent.com/42169660/53595970-ef77fb00-3b9e-11e9-8870-f39b437fb052.png)

Right, I might have missed something here, because I'm not getting the error in another implementation - but I'm looking into that right now.

**Comment by Frotty** [comment]
So just move onTimedLoop call?

**Comment by maltebp** [comment]
Yeah, I think that would be enough ;)

**Comment by Frotty** [comment]
Hi, does this fix it:
https://github.com/wurstscript/WurstStdlib2/pull/210
?

**Comment by maltebp** [comment]
I tested a similar fix, and yeah it seemed to fix it! However, I've made another implementation, since I needed some more features, so it's a bit tricky to test atm ;) But pretty sure this works.
