### ISSUE TITLE
LinkedList endless loop

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstStdlib2#199]
The following code produce an infinite loop:
https://bin.wurstlang.org/qotolanune.wurst

For some reason adding an element to a new list after removing it from its original list affects the latter in a buggy way.

**EDIT:**
Here is the output of the first code:
<img width="73" alt="bug0" src="https://user-images.githubusercontent.com/38940363/53633163-fe9a8f80-3c16-11e9-96e0-31a4029de11b.PNG">

The following code will result in a slightly different infinite loop:
https://bin.wurstlang.org/fuberuduko.wurst
<img width="69" alt="bug" src="https://user-images.githubusercontent.com/38940363/53633101-d3b03b80-3c16-11e9-8d68-df171ab29e03.PNG">

**EDIT2:**
Adding to the second list and then removing from the first will not produce this issue.

**Comment by Frotty** [comment]
You are removing an object from the list while iterating. In Java this would throw a concurrent modification exception. It is not allowed in a regular for loop. If you want to remove elements while iterating you need to while/from loop through the iterator and call remove on it, not the list.

**Comment by WareditorGit** [comment]
I was thinking you could do both with Wurst.
It should be noted that the HashList iterator's .remove() does nothing.

**Comment by Frotty** [comment]
> It should be noted that the HashList iterator's .remove() does nothing.

Wanna implement it :D ?
