### ISSUE TITLE
ClosureTimers as a timer extensions

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstStdlib2#200]
#168 
First: can we get old `.start` method back?
```
	function start(real time)
		t = getTimer()
			..setData(this castTo int)
			..start(time, () -> staticCallback())
```
we don't always need to keep the timer instance.

Second: it is not obvious that a callback instance releases its timer so we get `double free` exception.

**Comment by Frotty** [comment]
> First: can we get old .start method back

Why? Old functionality is still in place, you don't have to keep the timer instance, it's optional.

> Second: it is not obvious that a callback instance releases its timer so we get double free exception

Is this a suggestion or just comment? I would argue that most people use closure instances in a throw away manner. This would result in leaks in many cases.

**Comment by GetLocalPlayer** [comment]
> Why? Old functionality is still in place, you don't have to keep the timer instance, it's optional.

Now I have to import `TimerUtils` package and call `getTimer` manually, don't I? That's broken lots of code.

**Comment by Frotty** [comment]
> Now I have to import TimerUtils package and call getTimer manually, don't I? That has broken lots of code.

I suppose you are saving `CallbackSingle` in a variable, and then calling `.start`. This was never intended usage. You should use
`doAfter(1.0, myClosureVar)` just like before, but passing your instance instead of making a closure block.

**Comment by GetLocalPlayer** [comment]
> I suppose you are saving `CallbackSingle` in a variable, and then calling `.start`. This was never intended usage. You should use

Shoudn't `.start` method be protected then if it was designed to not be used out of the package?

**Comment by Frotty** [comment]
> Shoudn't .start method be protected if it was designed to not be used out of the package?

Yes, I suppose. It's just the reason I overlooked the breaking change in the PR - I thought it wouldn't be used from outside. Sry about that 😓

**Comment by GetLocalPlayer** [comment]
Now it's clear for me. Shall I make a PR then?

**Comment by Frotty** [comment]
> Now it's clear for me. Shall I make a PR then?

Sure. Close this then?
