### ISSUE TITLE
rename _wurst/assets/Abilities.wurst 

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#201]
https://github.com/wurstscript/WurstStdlib2/blob/9559ad20266a0417ab9eda1db5a989f4aac70939/wurst/_wurst/assets/Abilities.wurst#L4

"Abilities" is a very generic naming, maybe it could be called something like "SpellModels"

**Comment by Frotty** [comment]
Abilities is in line with all the other packages, which would also have to be changed.

**Comment by Krypt0n** [comment]
Yeah I know, just dues to conventions, I thougth it should had been given some other naming.
