### ISSUE TITLE
remove "move" and "smart" from OrderStringFactory

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#202]
https://github.com/wurstscript/WurstStdlib2/blob/9559ad20266a0417ab9eda1db5a989f4aac70939/wurst/objediting/presets/OrderStringFactory.wurst#L212
https://github.com/wurstscript/WurstStdlib2/blob/9559ad20266a0417ab9eda1db5a989f4aac70939/wurst/objediting/presets/OrderStringFactory.wurst#L290

I don't think that  "move" and "smart" should be use for an regular ability, am I right?

**Comment by Frotty** [comment]
Does it cause problems?

**Comment by Krypt0n** [comment]
it does, if you used to detect order commands for lastorder like move or right click (that is "smart") and you have the order command for some spell assigned
