### ISSUE TITLE
ChannelAbilityPreset enum Option should be renamed

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#203]
https://github.com/wurstscript/WurstStdlib2/blob/9559ad20266a0417ab9eda1db5a989f4aac70939/wurst/objediting/presets/ChannelAbilityPreset.wurst#L14

There should be a better naming then "Option" this is way to generic.

Alternatives:
AbilityOption
TargetOption
SpellOption
ChannelOption

**Comment by Frotty** [comment]
i don#t think any of these breaking changes make sense. rather wait for the compiler update to add specified imports.

**Comment by Krypt0n** [comment]
ok.
