### ISSUE TITLE
missing hidden natives?

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstStdlib2#206]
following natives seem to miss in wurst

```
native GetUnitMovementType                      takes unit whichUnit returns integer
native SetUnitMovementType                      takes unit whichUnit, integer movementType returns nothing
native GetUnitArmorType                         takes unit whichUnit returns integer
native SetHeroStatEx                            takes unit whichHero, integer whichStat, integer statValue, boolean permanent returns nothing
native GetHeroPrimaryStat                       takes unit whichHero returns integer
native GetHeroPrimaryStatById                   takes unit whichHero returns integer
native GetHeroStat                              takes unit whichHero, integer whichStat, boolean includeBonuses returns integer
native SetHeroPrimaryStat                       takes unit whichHero, integer whichStat returns nothing
```

/// edit: should be moved to https://github.com/wurstscript/WurstScript

**Comment by Frotty** [comment]
I guess it needs ticket here and compiler. What exactly are these hidden natives? Why are they not in common.j? Do they all work correctly? etc.

**Comment by Krypt0n** [comment]
I think all but `SetHeroPrimaryStat` should work fine
I can workout some test map with jass.
They are there since 1.29 but noone used them or put them into common.j
They planned to remove them but then since 1.30.2 they said they are keeping them for now.

**Comment by anufis** [comment]
Is it possible to use them similar to IsUnitAlive by declaring them as natives in mapscript.j if they are not in common.j?

**Comment by Krypt0n** [comment]
Yes, correctly:
https://bin.wurstlang.org/uhigoxihah.wurst

**Comment by Krypt0n** [comment]
what is missing right now is `BlzGetTriggerFrameValue ` which is used to get the slider value of an framehandle slider created with:
`framehandle fh  = createFrame("StandardSliderTemplate", getOriginFrame(ORIGIN_FRAME_GAME_UI,0), 0,0)`

**Comment by Frotty** [comment]
@Krypt0n Do you have an update on this?

**Comment by Krypt0n** [comment]
Sorrry no I was recently to busy. Would also need to check all stuff with the released wc3 version, but if I am not wrong this is no working atm, but it should, as its quite important for several custom ui elements.

**Comment by Frotty** [comment]
can be closed now?

**Comment by Legend94rz** [comment]
I want to use `BlzGetTriggerFrameValue` to deal with the wheel event of a slider frame, but now this native function is not included in common.j in wurst as we all know. How to solve this problem? 
I have tried to declare the function in a wurst file, that is, add the following line to a new wurst file:
`native BlzGetTriggerFrameValue  takes nothing returns real`
If we do so, the game cannot read the map and just says there is an error when loads the map.
Could any one help me?

**Comment by Krypt0n** [comment]
That function does not exist. Just use `BlzFrameGetValue`

**Comment by Frotty** [comment]
Okay so we should fix the documentation

**Comment by Legend94rz** [comment]
Thanks for your replies! @Krypt0n as far as I know, `BlzFrameGetValue` returns the current value of the frame (slider), but now I want to deal with the wheel event. It is necessary to judge the direction of the mouse wheel, and this information is offered by `BlzGetTriggerFrameValue`. Could you please add this function?

**Comment by Krypt0n** [comment]
I can make new PR later, and push into Framehandle.wurst then. I have anyway some change there, cause there is unsave could the things with `createFrame(string name)` that forces priority and context to 0, which should not be there in the stdlib at all. Its very dangerous, @WareditorGit  added it and if its needed for a local project, it should be added there.

**Comment by Legend94rz** [comment]
> It should be possible to just define them like the UnitAlive native though.

@Frotty Could you please explain more about how to define the hidden functions like `UnitAlive`? I have tried to do so, but it seems like it fails.  Here‘s what I did:
Firstly, I have a file named `slider.wurst`, which creates a slider and deal with wheel event. To declare the required hidden function `BlzGetTriggerFrameValue`, I have another file named `hiddens.wurst`, which has only one line reads `native BlzGetTriggerFrameValue takes nothing returns real`. However, this approach doesn't work. There is no error during building map, but when opening the map in game, it tells me the map has some error.  Am I correct?

In addition, I have tried to create a map by the native World Editor, then create a slider, and deal with wheel event by jass. It works fine. However, I want to use Wurst rather than jass since it's more convinient.

**Comment by Frotty** [comment]
Yea it will require a compiler update, @Krypt0n also reported that it doesn't work right now.
I guess UnitAlive is a special case.

**Comment by Frotty** [comment]
Nevermind, it should already work with `@extern`.
@Legend94rz please try adding this:
```
@extern native BlzGetTriggerFrameValue() returns real
@extern native BlzGetTriggerFrameText() returns string
```

**Comment by Legend94rz** [comment]
Thanks for your help! I tried to add these two lines, but it still doesn't seem to work.  PJass do report an error. What puzzles me is why the native world editor could find these natives and wurst cannot.

In addition, I added the two native declarations into common.j under the `_build` folder, but PJass still cannot find the functions. Am I wrong?

**Comment by Legend94rz** [comment]
I think this is a bug of PJass or wurst. I add `-noPJass` into `wurst_run.args` after adding declarations to common.j under the `_build` folder, and it works...
