### ISSUE TITLE
Object Reading

### ISSUE THREAD

**Issue by zhPavel** [wurstscript/WurstStdlib2#208]
There are Object Editing functions. Can you add Object Reading functions? It would be also convenient if they worked with Wrust-generated objects.

**Comment by Frotty** [comment]
Objects only save values they override. You can save those yourself if you so desire. 
The problem with generic getters is that you need the data of the base object, which would need to be read from the game files. 
There is a ticket https://github.com/wurstscript/WurstScript/issues/683
