### ISSUE TITLE
Add wrappers for 1.31 natives to PTR branch

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstStdlib2#228]
We created a new [branch ](https://github.com/wurstscript/WurstStdlib2/tree/ptr)

Related:
https://github.com/wurstscript/WurstScript/issues/841
https://github.com/wurstscript/WurstScript/issues/842

**Comment by Donach** [comment]
Anyone already started doing some work on this? Don't wanna do the same things twice...

**Comment by Krypt0n** [comment]
We should fristly update the jassinterpreter and then the stdlib, I guess?

**Comment by Frotty** [comment]
> jassinterpreter

Why?

**Comment by Krypt0n** [comment]
yeah then only the types i guess sry

**Comment by fe3dback** [comment]
List of new natives, consts, events:
https://github.com/wurstscript/WurstStdlib2/pull/231#issuecomment-490938848

**Comment by Frotty** [comment]
I think this is done.
Let me know if some native isn't wrapped @fe3dback 
Thanks 🍭
