### ISSUE TITLE
IterableMap has no forEach

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#229]
https://github.com/peq/wurstStdlib/blob/master/wurst/data%20structures/LinkedHashMap.wurst#L101

**Comment by Frotty** [comment]
seems pointless, just iterate over keys and get the value.

**Comment by Frotty** [comment]
PR if you wanna add.

**Comment by Cokemonkey11** [comment]
It's a small request, but it's valuable

```
function roundStart()
    booth_effects.forEach() entry ->
        let u = entry.key
        let list = entry.value
        while list.size() < 4
            let size = list.size()
            list.addtoStart(new DummyEffect(u, 100. + 50. * size))
```

**Comment by Frotty** [comment]
so PR?

**Comment by Cokemonkey11** [comment]
@Frotty what implementation would you like? Current iterator returns `HLIterator<K>`, so one example PR would look like:

- creates new KvIterator
- creates new method `kvIterator()`
- creates new KvCallback
- creates new `forEach() kvCallback` method

Is that ok? Do you want kvIterator public?

**Comment by Frotty** [comment]
Why do you need kvIterator for a `forEach`?

**Comment by Cokemonkey11** [comment]
What alternative do you propose?

**Comment by Cokemonkey11** [comment]
you da best
