### ISSUE TITLE
IterableMap has no KV iterator

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#230]
https://github.com/peq/wurstStdlib/blob/master/wurst/data%20structures/LinkedHashMap.wurst#L86

**Comment by Frotty** [comment]
seems pointless, just iterate over keys and get the value.

**Comment by Frotty** [comment]
status?

**Comment by Cokemonkey11** [comment]
Still wanted

**Comment by Frotty** [comment]
forEach returnes key-value pairs, I consider this done.
