### ISSUE TITLE
def..setDefenseBase(int val) doesn't set the defense value to the given value

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstStdlib2#24]
Instead, calling this sets it to zero for some reason, no matter the input.

**Comment by Frotty** [comment]
Please provide a minimal example that doesn't work.
Changing a wisp's defense base works:
![](https://i.imgur.com/WnaIDih.png)
![](https://i.imgur.com/C8KQInB.png)

**Comment by IgorSamurovic** [comment]
no fuck this I am retarded it works

jesus I need to kill myself already
