### ISSUE TITLE
Merge PTR branch into master

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstStdlib2#250]
@Krypt0n @Donach @WareditorGit @fe3dback
As a followup to https://github.com/wurstscript/WurstStdlib2/issues/228
Now that 1.31 is live, the PTR branch should be merged as soon as the PRs are done.

These are mising:
- [x] https://github.com/wurstscript/WurstStdlib2/pull/245
- [x] https://github.com/wurstscript/WurstStdlib2/pull/246

**Comment by WareditorGit** [comment]
I will work on DamageEvent.

**Comment by Donach** [comment]
Hello @Frotty 
About #245 , can you check it?
There should be no more open points, although it might use another review (if you didn't already).
Thanks.

**Comment by Frotty** [comment]
> I will work on DamageEvent.

Maybe make a new ticket for that then?
What exactly needs to be changed?

Anyway, ptr is merged, cheers 🍻
