### ISSUE TITLE
FrameHandle abs position info correction

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstStdlib2#254]
https://github.com/wurstscript/WurstStdlib2/blob/41572ac812d296a9a8a8d879be0608e1b4a27e62/wurst/_handles/Framehandle.wurst#L76

(0, 0) is the bottom left corner of the 4:3 screen. 
(0.6, 0.6) the top right corner of the 4:3 screen.

**Comment by Frotty** [comment]
@Krypt0n

**Comment by WareditorGit** [comment]
Okay the screen max position is (0.8,0.6) since the screen is 4:3

**Comment by Krypt0n** [comment]
might be true now, i had not time to test wiht new wc3 version, it should be intented to be .8, .6 but in first ptr 1.31 version only .6 .6 was addressable
