### ISSUE TITLE
group.enumUnitsAll() is broken

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstStdlib2#272]
'public function group.enumUnitsAll(boolexpr filter)
	for i = 0 to bj_MAX_PLAYER_SLOTS - 1
		this.enumUnitsOfPlayer(players[i], filter)'

Looks like `GroupEnumUnitsOfPlayer` overwrites the group each time it is called so the group only ends up with the last player's units

**Comment by jlfarris91** [comment]
I did this instead

public function group.enumUnitsAll()
  var tempGroup = getGroup()
  for i = 0 to bj_MAX_PLAYER_SLOTS - 1
    tempGroup.enumUnitsOfPlayer(players[i], null)
    tempGroup.addGroup(this) // This is backwards (issue #273)
  tempGroup.release()

**Comment by Frotty** [comment]
Please use [code fences](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) when pasting code.

I guess this was a mix up with `forUnitsAll` from the `ClosureForGroups` package (which you should use btw) where it's done via the closure param.

I pushed a fix using `ENUM_GROUP` and the fixed `addGroup`
