### ISSUE TITLE
The arguments of group.addGroup are backwards

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstStdlib2#273]
Looks like 'BlzGroupAddGroupFast' has the arguments backwards compared to 'GroupAddGroup'

**Comment by Frotty** [comment]
What do you mean?
Are you saying that `native BlzGroupAddGroupFast takes group whichGroup, group addGroup` adds `whichGroup` to `addGroup`?
Otherwise looks correct to me.

**Comment by jlfarris91** [comment]
Yeah, so I end up needing to write `groupToAdd.addGroup(theGroupIWantToAddTo)` in order to add `groupToAdd` to `theGroupIWantToAddTo`, which seems backwards to me. I'm also suggesting that it's a Blizzard's bug but thought you might want to know either way.

**Comment by Frotty** [comment]
Okay, weird, I pushed a fix.
