### ISSUE TITLE
How to Access UnitAnimations?

### ISSUE THREAD

**Issue by frederikaalund** [wurstscript/WurstStdlib2#275]
#260 introduced the UnitAnimations module. It seems like a really nice addition. However, I don't know how to actually use it. I've tried with:

    caster.setAnimation(UnitAnimations.Spider.attack.idx)

but it gives me the warnings:

    Could not resolve reference to variable Spider for receiver of type UnitAnimations.
    Could not resolve reference to variable attack for receiver of type unknown type.

Am I doing something wrong? I haven't used nested static classes in Wurst before.

**Comment by Cokemonkey11** [comment]
Hey @frederikaalund 

Thanks very much for reporting this. In truth, I created this package and then didn't use it - in my project I just [referenced the indices directly](https://github.com/Cokemonkey11/shovelers-vs-temps/blob/master/wurst/Hello.wurst#L91L96).

I think this is a case of not really tested package, but the data is valuable either way, so not many questions asked when the PR was made.

@Frotty - Frederika is right that `Spider` is not accessible this way.

Should I make a fast PR that changes the code structure, or is this actually a compiler issue?

// CC @peq 

Cheers,

**Comment by peq** [comment]
@Cokemonkey11 That part of static inner classes is not yet implemented, see https://github.com/wurstscript/WurstScript/issues/213#issuecomment-125770570

I'll look into the issue again and check how much work it would be to complete the feature.

**Comment by peq** [comment]
@Cokemonkey11 The compiler problems should be fixed now, but there are two issues with the library

- There are some Duplicate classes which should be removed or renamed.
- The members should be static constants so that they can be accessed from the outside.

Can you make a pull request to fix this?

**Comment by Cokemonkey11** [comment]
Thanks, @peq! #277 is the PR you asked for above.

Hey @frederikaalund - should we close this out?

**Comment by frederikaalund** [comment]
Thanks for the quick resolution on both the compiler side and in the standard library.

The `UnitAnimations` library is now usable for me. It's a really nice addition to the standard library.

Cheers!
