### ISSUE TITLE
UnitAnimations uses up common class names

### ISSUE THREAD

**Issue by frederikaalund** [wurstscript/WurstStdlib2#282]
The following reproduces the issue:
```
package Issue1

public enum Target
    FRIENDLY
    ENEMY
    SELF
```
```
package Issue2
import UnitAnimations
import Issue1

public let t = Target.FRIENDLY
```

This simple example gives the error message:
```
Reference to variable Target is ambiguous. Alternatives are:
 * class Target defined in line 14242 (C:\Projects\Archflame\_build\dependencies\wurstStdlib2\wurst\_wurst\assets\UnitAnimations.wurst)
 * enum Target defined in line 3 (C:\Projects\Archflame\wurst\Issue1.wurst)
```

First of all, I think that this should be fixed on the compiler level. That is, a nested class (e.g. `UnitAnimations.Target`) should not be considered when trying to instantiate a top-level class (e.g. `Target`).

In lieu of that, I think the `UnitAnimations` package should avoid using common class names such as `Target` or `Watcher` (there are probably more). Maybe prefix all the `UnitAnimations` classes with something such as `UA`.

I really like the new UnitAnimations package. It is so nice to do without raw integer animation indices. Thanks again for the quick resolution with the previous issue.

**Comment by Frotty** [comment]
Sounds reasonably

@Cokemonkey11 ?

**Comment by Cokemonkey11** [comment]
I agree the compiler should be adjusted.

I think the problem is somewhat mitigated/pushed elsewhere by removing AnimationNames from stdlib

// cc @peq

**Comment by frederikaalund** [comment]
Linking this issue with #280 (for my own reference).

**Comment by Frotty** [comment]
I don#t think a breaking change makes much sense now.
Now that the package isn't auto imported it also only causes problems when used.
You can make a compiler ticket for the nested name resolution, though it might be intended.
