### ISSUE TITLE
About dummy multi-target casting

### ISSUE THREAD

**Issue by yefq** [wurstscript/WurstStdlib2#284]
Why not add Root Ability ('Aro1') to dummy?
It's make dummy can't move or turn (But can change position or facing with code).
This effect make dummy can multi-target casting to large number of target (Even when casting to all units in map).

Of course, maybe somebody want dummy can issue "move" order, Root Ability made them unable to do so (Like Locust Ability, the effect can't stop even when remove Root Ability )...
But I don't think that's a very common requirement, and it really does make dummy multi-target casting faster and more reliable.

```
// compiletime
new AbilityDefinition(DUMMY_ROOT_ID, 'Aro1')

// createDummy
u..addAbility(DUMMY_ROOT_ID)..removeAbility(DUMMY_ROOT_ID)
```

**Comment by Frotty** [comment]
The `InstantDummyCaster` package uses a building for instant casting and works for most cases.
I guess the problem with `DummyCaster` is that the unit needs to turn to cast the spell in succession?
So this change makes it not need to turn?

**Comment by yefq** [comment]
In fact `InstantDummyCaster`  not always reliable (If the number of targets is large or the frequency is high).
If use Root Dummy, we can cast the spell in succession with `ForGroup`  just use single dummy unit.

I wrote a function earlier to revive creeps (InstantDummyCaster cast AncestralSpirit ability to dead unit, revive units like heroes), sometimes dummy may miss target If I don't use Root ability, because unit dead event happens everywhere.

And I wrote a dummy package base on Root Dummy, for purposes like this:
``` js
// groups entangle roots, only one dummy is required for any number of targets
// use the unmodified entangling roots ability here
let dummy = new Dummy(tar, AbilityIds.entanglingRoots, 1)..owner(owner)

// get caster change the duration of the skill
// buffData is a tunple from hero skill duration field
dummy.caster() 
..setAbilityDataReal(dummy.abilId(), 1, ABILITY_DATA_DUR,     buffData.duration)
..setAbilityDataReal(dummy.abilId(), 1, ABILITY_DATA_HERODUR, buffData.heroDuration)

forUnitsInRange(tar, area, true) (unit u) ->
    if u.isAliveVaildEnemyOf(caster)
        dummy..castTarget(u)..resetCooldown()
destroy dummy
```

**Comment by Frotty** [comment]
Okay, can you upload a test map to verify this or something?

I believe, not being able to remove the ability, prevents this from being an opt-in feature for the dummy caster.
I can imagine some devs are relying on dummy movement e.g. when attacking but this was never really an intended feature so I agree this could be changed. @Cokemonkey11 ?

@yefq Would you make a PR after discussion?

**Comment by yefq** [comment]
I made a test map with triggers, And I will submit a PR later.
[RootDummy.w3x](https://drive.google.com/open?id=1YQGr6TghyDwgPH5-cEFa4BlVZ4UxVNcQ)

**Comment by Cokemonkey11** [comment]
I haven't investigated deeply but I trust with a test map that we will see you're right.

My only comment is that in your pseudocode above, I think there is no need to define a new `AbilityDefinition` if there is no object data being set.

I don't understand why InstantDummyCaster would not work without root. Structure units and root units should have the same capabilities - no?

**Comment by yefq** [comment]
Define a new `AbilityDefinition` because I am worried about user may change ability `'Aro1'`.
If ability field `RootedTurning` is `TRUE`, It will makes Units need turn.
Unfortunately, This field of the hidden ability `'Aroo'` is `TRUE` if not we could just use it.

And I don't quite understand what is Structure units, Does it meant a building unit?
I went to see `InstantDummyCaster` package, dummy unit was not a building, It not much different from `DummyRecycler`, So I don't feel very clear.

**Comment by Cokemonkey11** [comment]
> Define a new AbilityDefinition because I am worried about user may change ability 'Aro1'.
If ability field RootedTurning is TRUE, It will makes Units need turn.

The justification is very good - thanks for explaining.

> And I don't quite understand what is Structure units, Does it meant a building unit?

Yes, it's the same. Sometimes blizzard has a synonym in game constants/interface.

>  I went to see InstantDummyCaster package, dummy unit was not a building, It not much different from DummyRecycler, So I don't feel very clear.

I'm not sure either - maybe @Frotty can comment.

**Comment by Frotty** [comment]
Hm yeah, looks like @Trokkin changed this in https://github.com/wurstscript/WurstStdlib2/commit/e2004c581e58f5336de67b631382b4e010523717#diff-a83269f941297f3319a9a32dd3cc7f60

and I overlooked it in PR. Doesn't seem intentional.
I think we could use the root abil there instead of a building now.

**Comment by Cokemonkey11** [comment]
@yefq did you want to do the PR?

if not, probably we can do this today

**Comment by Frotty** [comment]
@Cokemonkey11 https://github.com/wurstscript/WurstStdlib2/pull/286

**Comment by yefq** [comment]
> 你想做公关@yefq？
> 如果没有,也许我们今天可以做到这一点

I submitted a PR before (#286), maybe that can be used.
But I am not very familiar with github, because my English is not very good...
If it has any problems, you may need to help it...

**Comment by Frotty** [comment]
It's merged 🎉
