### ISSUE TITLE
"AbilityDefinitionIllidanMetamorphosis" doesn't work

### ISSUE THREAD

**Issue by DoctorRyner** [wurstscript/WurstStdlib2#289]
It simply doesn't work if I set alternative form that way, maybe we need to create a simple morphing preset like with channel?

```Haskell
@compiletime function morphGen ()
    new AbilityDefinitionIllidanMetamorphosis (morphId)
        ..presetNormalFormUnit    (_ -> heroId.toString ())
        ..presetAlternateFormUnit (_ -> heroId2.toString ())
        ..presetCooldown          (_ -> 5)
        ..presetDurationHero      (_ -> 2)
        ..presetDurationNormal    (_ -> 0.5)
```

**Comment by Frotty** [comment]
Specify "doesn't work"  😐

**Comment by DoctorRyner** [comment]
presetAlternateFormUnit is lambda (int -> string), how should I convert that then?

**Comment by Frotty** [comment]
IdGenerators return `int`s and if you write `int i = 'h000'` it is quite obvious that `i` is an `int`.
Single quotes in jass and wurst are just base 256 `int`s (with some restrictions) to have more recognizable format.
`int.toString()` returns the numerical representation in base 10 e.g. `34123974`, not base 256.

---

Use `int.toRawCode()` or even better `commaList` from the `ObjectIds` package, the second supporting a variable amount of arguments, returning a comma separated list of ids used for e.g. normal spells, built structures, etc.
```
..presetNormalFormUnit    (_ -> commaList(heroId))
```

**Comment by DoctorRyner** [comment]
Thank you, that works perfect! Im just not used to these low level things, we in Haskell include something like this in a type level :)

**Comment by Frotty** [comment]
No problem. You can suggest information to be added to the website if you think something is missing.
https://github.com/wurstscript/wurstscript.github.io
