### ISSUE TITLE
What happend to effect orientation?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstStdlib2#297]
`mat3` and `quat` don't provide correct effect orientation anymore

![ezgif com-optimize(1)](https://user-images.githubusercontent.com/19322847/65673586-1e365100-e05c-11e9-8c77-66005fa207e1.gif)

Was there any change in BlzSetSpecialEffectOrientation in recent patches that I missed?

**Comment by Frotty** [comment]
I don't know. The only significant change to matrices was this https://github.com/wurstscript/WurstStdlib2/commit/f6d04d5bbe063fca552429f04992a2f3637b5dbb#diff-a507ebce03a413279c271d3c6f0268c5 and nothing else should have changed from what I know. (optimizations disabled?)

**Comment by GetLocalPlayer** [comment]
The problem is the game. That's how it works in 1.29 and how it must work

![ezgif com-optimize(2)](https://user-images.githubusercontent.com/19322847/65675809-d6192d80-e05f-11e9-9107-56730613300b.gif)

But I haven't seen it in the patch notes.
