### ISSUE TITLE
LinkedList remove() to return bool

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstStdlib2#302]
I want to know if calling LinkedList.remove actually removed the item. Currently I would need to call has(myItem) first to see if the item would be removed and then call remove(myItem) which means, in the worst case, iterating through the list twice.

```
/** Removes the first occurence of t from this list */
function remove(T elem) returns bool
  var entry = dummy.next
  while entry != dummy
    if entry.elem == elem
      removeEntry(entry)
      return true
    entry = entry.next
  return false
```

**Comment by Frotty** [comment]
Please open stdlib issues in the appropriate repository.

Regarding the problem, `remove` should probably just return the element like `removeAt` does.
Then you can check that for null.

**Comment by jlfarris91** [comment]
Shoot sorry about that, will do next time. That sounds fine too, however, it does seem a little strange to return the object that I'm already passing in.

**Comment by GetLocalPlayer** [comment]
> Regarding the problem, `remove` should probably just return the element like `removeAt` does.

Sound more like `.pop` method.
