### ISSUE TITLE
I can not find “native BlzFrameAddText takes framehandle frame, string text returns nothing”

### ISSUE THREAD

**Issue by HarounGY** [wurstscript/WurstStdlib2#314]
i can not find “native BlzFrameAddText takes framehandle frame, string text returns nothing”。

Did you forget it or something else？

**Comment by Frotty** [comment]
Nope, Blizzard forgot them, they are not part of the game's `common.j` file which we simply extract.

**Comment by HarounGY** [comment]
thanks！

**Comment by HarounGY** [comment]
hi Frotty
 i want to use this function，what can i do？

**Comment by Frotty** [comment]
You can edit your `common.j` file and disable Pjass.
That's not recommended though.

**Comment by HarounGY** [comment]
thanks
