### ISSUE TITLE
Player Mouse Position

### ISSUE THREAD

**Issue by maltebp** [wurstscript/WurstStdlib2#338]
Been using a library to keep track of player mouse position for quite a while (and quite a lot) in my own maps, and I just considered that it may an interesting utility feature to have in the standard library.

It's a small, so I'll post the code here for now

```

package PlayerMouse

//================================================================================================================================================================================================
/*  
    Small Library to register all player's mouse movement, and constantly
    keep track of their positions.

    Warning:
     - The mouse position is vec2(0,0), if mouse is hovering over UI elements
     - If the Player's camera is moved, and thus also the mouse, the mouse position is NOT updated
*/
//================================================================================================================================================================================================

import RegisterEvents
import ErrorHandling

@configurable public let ENABLED = true

vec2 array mousePosition

/** Returns the position of this player's mouse in map coordinates. */
public function player.getMousePos() returns vec2
    if not ENABLED
        error("PlayerMouse: Library is not activated!")
    return mousePosition[this.getId()]
    
init
    if ENABLED
        registerPlayerEvent(EVENT_PLAYER_MOUSE_MOVE) ->
            mousePosition[GetTriggerPlayer().getId()] = vec2( BlzGetTriggerPlayerMouseX(), BlzGetTriggerPlayerMouseY() )
         
```

There are a few problems with the library, as mentioned in the comments in the code, but I consider the fact that moving the camera in other manners (i.e. arrow keys) isn't updating the updating the mouse pos, the biggest problem.

**Comment by Frotty** [comment]
> There are a few problems with the library, as mentioned in the comments in the code, but I consider the fact that moving the camera in other manners (i.e. arrow keys) isn't updating the updating the mouse pos, the biggest problem.

Additionally it's also (0,0) if there is no terrain below the mouse in view direction.
Overall it's quite buggy and I don't think it should be a "recommended" stdlib feature as of now,
but maybe the coming patches change something.

**Comment by maltebp** [comment]
Right, I get ya - it's a small lib anyway, so it's easily implemented on your own if you need it.

Also, rather curious that no this functionality doesn't exist natively.
