### ISSUE TITLE
AnimationCallbackPeriodic

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstStdlib2#352]
Not sure about creating a PR.
A periodic abstract class with fixed ANIMATION_PERIOD from ``Basics`` package that uses only one timer

<details>

<summary>Code</summary>

```
public abstract class AnimationCallbackPeriodic
	private static let t = CreateTimer()
	protected static thistype first = null
	protected thistype prev = null
	protected thistype next = null

	construct()
		if first != null
			first.prev = this
			next = first
		else
			t.startPeriodic(ANIMATION_PERIOD, function staticCallback)
		first = this

	protected abstract function call(thistype cb)

	private static function staticCallback()
		var cb = first
		while cb != null
			cb.call(cb)
			cb = cb.next

	ondestroy
		if next != null
			next.prev = prev
		if prev != null
			prev.next = next
		else
			first = next
			if first == null
				t.pause()

/** Creates a periodic callback with ANIMATION_PERIOD you can configurate in "Basics" package. */
public function doPeriodically(AnimationCallbackPeriodic cb) returns AnimationCallbackPeriodic
	return cb
```
</details>

**Comment by Frotty** [comment]
> Not sure about creating a PR.

Not sure what you expect from posting some code snippet in a ticket.

> A periodic abstract class with fixed ANIMATION_PERIOD from Basics package that uses only one timer

For what purpose? Saving a handful timers? I think in most cases where this would make sense you should simply use TimedLoop, which already pools timers by timeout, see TimedLoopTimer.
If a lambda like in your snippet were to be added, that should probably also make use of the pool instead of a fixed timeout.

**Comment by GetLocalPlayer** [comment]
> Not sure what you expect from posting some code snippet in a ticket.
Understanding what I was talking about.

**Comment by Frotty** [comment]
> Understanding what I was talking about.

I don't understand. You didn't add any explanation.
Also you don't need to close tickets that need no closing.

**Comment by GetLocalPlayer** [comment]
> You didn't add any explanation.

Is anything not clear? A periodic closure that's rid of excessive `handle` creation and unnecessary recycling. Less work for a regular task (such as projectile moving).

> Also you don't need to close tickets that need no closing.

I'm getting the answer - I'm closing the ticket. Does it work different here?
