### ISSUE TITLE
vec2.isTerrainWalkable() always returns false

### ISSUE THREAD

**Issue by Jaccouille** [wurstscript/WurstStdlib2#368]
Hello there,

The id defined for the [dummy item id](https://github.com/wurstscript/WurstStdlib2/blob/3bafba6abc4b8ce19361f7ef8e679737b589a8d0/wurst/util/TerrainUtils.wurst#L60), which is used to check walkability, used to be `wolg`, which is a base id for the `Wirt's Other Leg` item, it has been replaced by a generated one in this [commit](https://github.com/wurstscript/WurstStdlib2/commit/3bafba6abc4b8ce19361f7ef8e679737b589a8d0) but the generate id isn't used in any object definition.

This [variable](https://github.com/wurstscript/WurstStdlib2/blob/3bafba6abc4b8ce19361f7ef8e679737b589a8d0/wurst/util/TerrainUtils.wurst#L61) end up being `null` since there's no item linked to the `DUMMY_ITEM_ID`.

This is causing the [dummyItem.getPos()](https://github.com/wurstscript/WurstStdlib2/blob/3bafba6abc4b8ce19361f7ef8e679737b589a8d0/wurst/util/TerrainUtils.wurst#L76) call to always return `(0, 0)` and therefore, the method isTerrainWalkable() always returns false.

Is `createItem(DUMMY_ITEM_ID, ZERO2)` supposed to not return `null` when the `DUMMY_ITEM_ID` doesn't refer an item that has been defined? Or @Frotty forgot to create an ItemDefinition for the dummy item?

**Comment by Frotty** [comment]
It's already fixed and reverted to 'wolg'

**Comment by Jaccouille** [comment]
True, my bad.
