### ISSUE TITLE
Memory leaks in ClosureEvents?

### ISSUE THREAD

**Issue by tester1101** [wurstscript/WurstStdlib2#410]
[important!]
I was using pre1.29 version, so I updated ClosureEvents but this issue didn't disappaer. This may need to be checked in recent lib.

===============================================================================
Let's create an empty map and try compiling these codes.
 
[must needed]
[part 1]
```
package TestCode
import ClosureTimers

init
	doPeriodically(0.01) (CallbackPeriodic cb) ->
		createUnit(Player(0), 'hgry', vec2(0,0), angle(0)) 
		..hide()
		..setTimedLife(0.1)
```
			

[optional]
This is simply made for detecting leaks caused by 'handles'. You can use other code you have for debugging.
[part 2]
```

package HandleProfiler
import ClosureTimers

function getNewOffset() returns int
	let g = CreateGroup()
	let id = g.getHandleId()
	g.destr()
	return id - 0x100000

class ProfilerVars
	static int maxOffset

init
	doAfter(1.0) -> 
		let offset = getNewOffset()
		ProfilerVars.maxOffset = offset
		doPeriodically(1.0) (CallbackPeriodic cb) ->
			let newOffset = getNewOffset()
			if newOffset > ProfilerVars.maxOffset
				let increase = newOffset - ProfilerVars.maxOffset
				var str = "max handle offset increased from "
				str += ProfilerVars.maxOffset.toString() + " to "
				str += newOffset.toString() + ", +" + increase.toString()
				print(str)
				ProfilerVars.maxOffset = newOffset

```

If you run these code, you will see the message that max handle offset is increasing more and more. This means that memory is leaked by something.

I found that leaking is caused in ClosureEvents.

[part 3]
```
// Un/Register Events when unit enters map
onUnitIndex(() -> registerEventsForUnit(getIndexingUnit()))
onUnitDeindex(() -> unregisterEventsForUnit(getIndexingUnit()))
```

if you edit this,
[part 4]
```
// Un/Register Events when unit enters map
onUnitIndex(null)
onUnitDeindex(null)
```
You can see that max handle is no more inflating.

#note! Because of war3 internal problem, making a unit always leak. So also in this case, you can see the war3's memory increasing in task manager
[Things that always leak](https://www.hiveworkshop.com/threads/memory-leaks.263410/#C4)

Edit : I added references for each code block.

**Comment by Frotty** [comment]
What's the problem? Seems expected for handle counter to increase when events are registered.
But neither handle counter nor windows memory usage haven't been reliable measures for a while now, both of them recycle/reset.
I have run maps extensively using closure events with no problems for hours, so I don't think it matters.

**Comment by tester1101** [comment]
Thanks for the reply.
 There is one thing I want to check first.
 Can you see that the maximum handle value goes up when you run the code [part1] as I wrote in the post?

**Comment by tester1101** [comment]
Considering your comments, I tried a few things. And I came to the following conclusions: 

1.
  I tested the [part1] code for a long time and it didn't encounter fatal as quickly as I expected.
  On the contrary, the game ran fine for a much much longer than I expected. (I faced a fatality when the max handle went over 922500.)
  So, as you said, I haven't identified any significant problems.

2. As you mentioned, the method of detecting memory leaks by increasing the maximum handle value is not reliable. 

3. What is the memory leak detection method you recommend?


Below are about how I reached these conclusions.
==============
You said,
"neither handle counter nor windows memory usage have been reliable measures"

It's the opposite of what I've been taught for a long time.

 When I was in the early days of map production, I had a game crash (fatal) due to an effect leak.
 Since then, I've been aware of memory leaks and have seen several posts trying to get rid of them by designating them as absolute evil.
 And I came up with a way to check for memory leaks by updating the max handle value.
 I also used this to catch a lot of leaks when I was using vjass .

 So what you said was a little questionable, and I decided to experiment.
 The content of the experiment is to measure the point at which the game suffers a fatality and is forcibly terminated when the maximum handle value is reached if the above [part1] is continuously executed.

 As a result.
 I faced a fatal when [max handle value 923000, memory usage 1.1GB]
 
 That's right. It is 923000. It's not the 92300. This means that the [part1] code will have to create more than 900,000 (...) units during the game to suffer a memory failure.

 This was far beyond my expectations. In the early days of map making, I suffered a fatality even when there were over a thousand effect leaks, but in the case of the code above, the game runs fine even when it reaches 900,000.
 And above all, right before the fatal, there were no frame drops in the game.

 This experiment made me realize that leak detection methods that measure the maximum handle value increase are unreliable, and handle increases caused by ClosureEvents are also fine.

**Comment by Frotty** [comment]
> It's the opposite of what I've been taught for a long time.

It was true for earlier patches I suppose. Thanks for posting your results.
The main takeaway imho is that you should worry about performance issues when you face them and not try to optimize prematurely.
