### ISSUE TITLE
Naisha Sentinel ID

### ISSUE THREAD

**Issue by SCARaw** [wurstscript/WurstStdlib2#438]
Hellow 
i know you got Sentinel ID listed as Aesn
However in Warcraft 3 campain there is a girl Naisha
shes Lt of Maiev and her Sentinel can be used multiple times and have different id
Could you find me her ID?
i do run OG warcraft 3 frozen throne :)
and i can't find it anywhere

**Comment by Frotty** [comment]
The IDs in the std lib are for base spells. The campaign spells are custom and therefore not available to simply use as base ID.
You can probably change some values for the spells to get what you want, others might require custom code and would need to be extracted from the campaign maps, or recreated yourself. In any case, this seems unrelated to WurstScript. Consider asking for help in the Wurst/Hive discords or in hiveworkshop forums.

**Comment by SCARaw** [comment]
thank you
