### ISSUE TITLE
AbilityDefinitionPotionofLifeRegen -> setAllowWhenFull

### ISSUE THREAD

**Issue by Kithio** [wurstscript/WurstStdlib2#44]
Currently this value is set to "String" which isn't correct. It'll give an invalid value no matter what you input.

The value it should be is an int since in the background in the Editor, it's an integer value. While it might show "Never" "Life Only" "Mana Only" "Always" the real values are as follows

Never = 0
Life Only = 1
Mana Only = 2
Always = 3

**Comment by draftlord** [comment]
The same thing is true for AbilityDefinitionRejuvination.

**Comment by Frotty** [comment]
Thanks, I have replaced it with an enum.
@IgorSamurovic wanted to regenerate the Assets packages at some point to solve these inconsistencies
