### ISSUE TITLE
Naming Inconsistency on Functions (setArtTarget / setTarget)

### ISSUE THREAD

**Issue by Kithio** [wurstscript/WurstStdlib2#45]
In AbilityDefinition the function for setting TargetArt is `setArtTarget` while in BuffDefinition it's  `setTarget`. I'd suggest changing BuffDefinition to `setArtTarget` to match the one found in AbilityDefinition.

**Comment by Frotty** [comment]
Yeah that's probably better. I have created ArtTarget and ArtSpecial and deprecated the old ones.
