### ISSUE TITLE
Buffer Error in Serialization (writeBoolean)

### ISSUE THREAD

**Issue by Kithio** [wurstscript/WurstStdlib2#46]
Currently if you attempt to write a boolean value into your buffer it will not get a separator resulting in invalid data as the values are loaded in segmented chunks seperated by the "TERMINATOR" or the symbol "|"

Another problem with the system is that Booleans in general aren't being read properly. You're saving booleans without a Terminator at the end while other values are saved with a terminator. That alone brings inconsistency to the code format in the file.

Because of this, the way you read Booleans right now seems to be popString(1) where 1 is the length of how much you want to read... This brings out issues in the code and I suggest adding

`pushTerminator()` to the end of `writeBoolean` inside the `StringBuffer` class along with changing the `readBoolean` function to instead do it's check on `popUntilTerminator()`

I can create a PR of the changes that fixed the problem locally for me if you'd like.

Note -- This post may be a bit jumbled, writing this after having been up for 30+ hours and on my phone. so excuse any issues in writing please.

**Comment by Kithio** [comment]
To just clarify this real quick before I head to bed...

L594 in Buffer.wurst add `pushTerminator`

L622 in Buffer.wurst change return to `popUntilTerminator()` instead of `popString(1)`

**Comment by SamuelMoriarty** [comment]
Can you provide a test case for when this decoding fails, and explain how exactly it fails?

Let me explain the rationale behind this format, and emphasize this was chosen deliberately.
The format is optimized for space, with the most minimal plain-text encodings in it that I could conceive at the moment.

The terminator character is supposed to be only used as literally that - a terminator, particularly for ints and reals. The general decoding scheme is meant to go like this:
1. read type identifier (i for int, r for real, s for string, b for boolean)
2. if it is real or int, load up all characters up until the terminator character (|), then convert it into the number and return
3. if it is a string, read the string length up until the terminator character, convert string length to int, and read the necessary amount of characters for the string, and return
4. if it is a boolean, we simply read a single character and convert it to boolean

That way, booleans only take 2 bytes. Including a terminator character would make them 3 bytes.

I don't understand where you got the idea that "the values are loaded in segmented chunks seperated by the "TERMINATOR" or the symbol "|"`"
If you are talking about the function `popUntilTerminator()`, then that function is only used in the decoding of reals and ints, as I explained above.

If this is really causing an issue for you, then please, provide a test case that reproduces the issue and the relevant error messages/symptoms.

**Comment by Kithio** [comment]
After a clean wipe of my entire setup, this was no longer an issue.

I'm going to guess it was overlapping files from pulling the updated library through github directly instead of using the wurst setup tool that caused some weirdness in memory when building the map.
