### ISSUE TITLE
Add Hurl Boulder

### ISSUE THREAD

**Issue by MediumRareSteak-Hive** [wurstscript/WurstStdlib2#62]
Just wanted to add a simple class for AbilityObjEditing, if it doesn't already exist.

{code}
public class AbilityDefinitionHurlBoulder extends AbilityDefinition
    construct(int newAbilityId)
        super(newAbilityId, 'ACtb')

    function setDamage(int lvl, real value)
        def.setLvlDataUnreal("Ctb1", lvl, 1, value)

    function presetDamage(RealLevelClosure lc)
        def.setLevelsDataUnreal("Ctb1", lvls, 1, lc)
        addTooltipProperty("Damage", lc)
{code}

**Comment by Frotty** [comment]
Oh hi, I missed this because I thought it was a PR 🍡 
Thanks for the report, but this ability already exists under it's slk name `AbilityDefinitionThunderBoltCreep`
https://github.com/wurstscript/WurstStdlib2/blob/master/wurst/objediting/AbilityObjEditing.wurst#L16323
