### ISSUE TITLE
Some Changes

### ISSUE THREAD

**Issue by MediumRareSteak-Hive** [wurstscript/WurstStdlib2#66]
_build\dependencies\wurstStdlib2\wurst\_handles\Unit.wurst: (Added function)
public function unit.isIllusion() returns bool
    return IsUnitIllusion(this)

_build\dependencies\wurstStdlib2\wurst\_handles\AbilityObjEditing.wurst (Added functions)
    public class AbilityDefinitionElunesGrace extends AbilityDefinition
        ....

        function setMagicDamageReduction(int level, real value)
		def.setLvlDataUnreal("Def1", level, 1, value)

	function presetMagicDamageReduction(RealLevelClosure lc)
		def.setLevelsDataUnreal("Def1", lvls, 1, lc)
		addTooltipProperty("MagicDamageReduction", lc)

	function setDamageTaken(int level, real value)
		def.setLvlDataUnreal("Def5", level, 5, value)

	function presetDamageTaken(RealLevelClosure lc)
		def.setLevelsDataUnreal("Def5", lvls, 5, lc)
		addTooltipProperty("DamageTaken", lc)

I added some of these for my own convenience but I think these are some useful functions.

**Comment by Frotty** [comment]
Why don't you make a PR?

**Comment by Cokemonkey11** [comment]
It looks like you've already made those changes and you're using them - is that right? If so, consider sending a pull request so we can copy your work - https://www.thinkful.com/learn/github-pull-request-tutorial/
