### ISSUE TITLE
Improve Assets.wurst

### ISSUE THREAD

**Issue by Trokkin** [wurstscript/WurstStdlib2#8]
As I understood, the package is designed to store every default wc3's model, icon or sound as a string constant in a corresponding class; I was using it heavily in last week and noticed that it a) misses many assets (for example, lavaspawn missiles) b) misses proper categorization, since most assets are stored in Other class.
At it's best I'd like to see categorization as what it was in object editor, plus adding Heroes and Buildings tabs (it's easy because their paths always contain "hero" or "building"), and probably remix missiles, spells and effects to Auras, Buffs (effects that are placed on unit continuously), Missiles and Effects (instant one-time effect)
And I would do it if I were assigned to.

**Comment by Frotty** [comment]
Icons were supposed to be delivered via an icon picket, but @Crigges never finished his work on that.

All other assets except Textures are there, since texture paths are rarely used.
Lavaspawn missiles and other models are already inside.
![](https://i.imgur.com/c1Jo7bG.png)
Since this data has been generated from the wc3 mpq's listfiles.

In general, please be more specific with your ticket descriptions, and what exactly you want to change/add.
Having extra Categorization would be nice, but would also break compatibility now.

**Comment by Trokkin** [comment]
But @Frotty, this is sounds, but not missile models!
Aside from this, there's also no Incinerate models, and that's what I've found while I was searching fire-themed effects - there could be plenty of models missing.

**Comment by Frotty** [comment]
Yea I see. Models inside the Abilities Folder apparently weren't parsed. I have written a new small snippet that has new categories.
I put it into a gist for you to try out: https://gist.github.com/Frotty/645f16b82794b7e60cf8c9d9436de427
Let me know if this contains everything now.

**Comment by Trokkin** [comment]
Well, it seems that it has the abilities I didn't see earlier. But I see Buildings category pretty small... It should be bigger I think. I'll try to merge this and current Assets and see if it do better.

**Comment by Frotty** [comment]
You shouldn't merge, but instead adjust this script to generate the complete asset package.
https://gist.github.com/Frotty/5433ef30aebfaa8a1d8ba57f2e4914df
I will commit it to the wurstscript repo soon.
Buildings category is small because only paths beginning with "buildings/" are added to it.

**Comment by Trokkin** [comment]
I guess it shouldn't be sensitive to letters register, is it?
Yet I think some sortage could be done only manually, though it would be pretty good to have different categories for missiles and for portraits - that would require check for name's suffixes,... its still very cool. I'd try do what I want to see here, though I had no practise in java for a long while, I hardly understand what's going on there. But I will try, eventually.

**Comment by Frotty** [comment]
Let me know when you have improvements to make. I will push the update for now.
